### ISSUE TITLE
Does it support parallel runs?

### ISSUE THREAD

**Issue by mudrd8mz** [andrewnicols/moodle-browser-config#4]
I am trying to combine this with `$CFG->behat_parallel_run` but it does not seem to work for me. Are parallel runs supported somehow?

**Comment by mudrd8mz** [comment]
Please ignore this. It seems I had problem elsewhere.

**Comment by andrewnicols** [comment]
I’ll answer this anyway, and I’ll think about how best to describe this in README.md.

The `$CFG->behat_parallel_run` configuration allows you to specify _changes_ to the profile for each run.

Both Selenium, Chromedriver, and Edgedriver, all support having multiple sessions from a single driver process. So I can start up to about 8 separate Chrome session for a single chromedriver binary. Selenium has configurable slots too. This means that you can actually just run a parallel run as normal with one instance of Selenium, Chromedriver, or Edgedriver and it will just work.

Geckodriver is the odd one out and if you are running with the `geckodriver` or `headlessgeckodriver` profiles you can only have one browser session per instance of geckodriver.

If you do want to run multiple driver instances then you’ll have to configure it. You’ll _need_ to do so for geckodriver, and you can_choose_ to do so for Selenium/Chromedriver/Edgedriver where there _may_ be a performance improvement (possibly - we assume). To do so, you’ll need to configure some custom browser profiles as per the examples which look like:

```

<?php

use AndrewNicols\Behat\ProfileManager;

$profiles = [];

for ($i = 1; $i <= 3; $i++) {
    // This is a hacky way to copy a profile.
    // We'll add a better way in future.
    $profile = array_merge([], $CFG->behat_profiles['headlessgeckodriver']);
    $profile['wd_host'] = str_replace('4444', 4444 + $i - 1, $profile['wd_host']);
    $profiles["headlessgeckodriver{$i}"] = $profile;
}

return $profiles;
```

You will then need to run multiple copies of geckodriver (or whichever driver you’re running) on ports 4444, 4445, 4446, etc.

Then, when you run behat you can provide a `--replace={run} --profile=headlessgeckodriver{run}`

As I say, that is unlikely to be required for use with Chrome, but will be required for Geckodriver _if used without selenium_.

I’ve added the above example to the examples directory, and am happy to accept a pull request to clarify the behaviour above.

**Comment by mudrd8mz** [comment]
Ugh. I must admit I am getting lost on all the layers and components in here, sorry. Not anyone's fault, just lack of time here to dive into it deeply. I think I managed to get Behat running in parallel locally with headlesschrome against three instances of selenium on three different ports.

**Comment by stronk7** [comment]
For the records, @andrewnicols pointed me to this, because I was asking him the very same thing...

I think that `$CFG->behat_parallel_run` continues working exactly the same, the only (important) detail... is that it doesn't set the profiles `wd_host` but the default one (at the top of the generated `behat.yml` file, together with all the contexts, tags... that are automatically inherited by profiles, suites... and other elements...

I've checked here and I've found in my `behatX.yml` files that I've this:

```
  extensions:
    Behat\MinkExtension:
      base_url: 'http://127.0.0.1/~stronk7/behattesting/behatrun1'
      goutte: null
      webdriver:
        wd_host: 'http://127.0.0.1:860X/wd/hub'
```

So, effectively, it's being set as it used to.

But the problem is that, using this tool, it's never used because this tool sets the `wd_host` for every profile, hence... there isn't any default to apply, profile one wins.

That's my theory, so far. Haven't tried now because I'm in the middle of a parallel-3 run and cannot break it now!

Ciao :-)
